

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
      mode: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update
    show-sql: true